# Este usa: Reader_and_Writer_VAde, Vertice_VAde, e Intento_Solution_Generator.
# Con el prueba3.txt.

EJEMPLAR = orb06.txt

generar_sol_aleatoria_y_makespan: 
	@python3 Version_Sol_Aleatoria_Makespan.py $(EJEMPLAR)

generar_vecindad:
	@python3 Version_Generadora_Vecinos.py $(EJEMPLAR)

EJEMPLAR = swv10.txt

reparadora_prueba:
	@python3 Version_Reparadora.py $(EJEMPLAR)