 
a:
	@python3 Version1.py 

b:
	@python3 Version2.py 

clean:
	@rm Pruebita_Inventada.txt

# Este usa: Reader_and_Writer_VAde, Vertice_VAde, e Intento_Solution_Generator.
# Con el prueba3.txt.
generar_sol_aleatoria: 
	@python3 Version_Ade.py
